### ISSUE TITLE
PHP 5.6 not working

### ISSUE THREAD

**Issue by mfeltscher** [cloudfoundry/php-buildpack#128]
Hi

I'm trying to run my apps using PHP 5.6 but somehow that's not working. My `.bp-config/options.json` looks like this:
```
{
"PHP_VERSION": "{PHP_56_LATEST}",
"WEB_SERVER": "nginx",
"ZEND_EXTENSIONS": ["opcache"],
"PHP_EXTENSIONS":["bz2","zlib","curl","mcrypt","mbstring","intl","openssl"],
"WEBDIR": "web",
"COMPOSER_VENDOR_DIR": "vendor/",
"COMPOSER_INSTALL_OPTIONS": [ "--no-dev"]
}
```

For some reason PHP 5.5.30 gets installed (also confirmed using `phpinfo()`):
```
-------> Buildpack version 4.3.1
Installing Nginx
Downloaded [file:///tmp/buildpacks/6081a977e3464fc53293668f83749b41/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_nginx_nginx-1.8.0-linux-x64.tgz] to [/tmp]
Installing PHP
PHP 5.5.30
```

What am I doing wrong here?

Thanks
Moreno

**Comment by dmikusa-pivotal** [comment]
Set BP_DEBUG=true and try again.  Attach the output here.

https://github.com/cloudfoundry/php-buildpack/blob/master/docs/troubleshooting.md#enable-debug-mode

**Comment by mfeltscher** [comment]
While looking at the output using `BP_DEBUG=true` I found the issue:
```
2016-01-18 12:43:51,397 [DEBUG] composer - Composer picked PHP Version [>=5.5]
2016-01-18 12:43:51,398 [DEBUG] utils - line #143 in /tmp/buildpacks/6081a977e3464fc53293668f83749b41/extensions/composer/extension.py, "configure" is setting [PHP_VERSION] = [5.5.30]
```

The corresponding setting in `composer.json` looks as follows:
```
...
    "require": {
        "php": ">=5.5",
...
```

IMO this is a bug, since PHP 5.6.x is `>=5.5`. Why does the setting in `composer.json` override the value I set in `options.json`?

**Comment by dmikusa-pivotal** [comment]
From the docs...

>The following format is supported for PHP version numbers. This is a small subset of the format supported by Composer.

>Example	Expected Version
>  5.5.*	latest 5.5.x release
> >=5.5	latest 5.5.x release
> 5.5.x	specific 5.5.x release that is listed

https://github.com/cloudfoundry/php-buildpack/blob/master/docs/composer.md

In other words, the build pack interprets ">=5.5" to mean the latest 5.5 release, not the latest of any release.  You can see this in the code [here](https://github.com/cloudfoundry/php-buildpack/blob/master/extensions/composer/extension.py#L94-L108).

I agree that a more sophisticated version selection implementation cloud be nice.  Especially if it's more inline with how Composer determines the version.  Or better yet, if there's some way to shell out and get that from Composer so that the logic is not duplicated in the build pack.  As usual, PR's welcome.

**Comment by mfeltscher** [comment]
Is there support for values like `>=5.5|>=5.6`?

**Comment by dmikusa-pivotal** [comment]
The build pack only supports the three permutations listed in the docs.  Anything additional, like `>=5.5|>=5.6` would require code change.

**Comment by mfeltscher** [comment]
OK, got it. What about changing `>=5.5` to install the latest PHP release (in this case this would be PHP 5.6)? Do you allow breaking changes like this?

**Comment by dmikusa-pivotal** [comment]
Not sure.  Probably depends on when it get's pulled in, like if it's changed between major build pack versions.  @Dannyzen is guiding the future of the PHP build pack now.  He would be the one to answer this question.

**Comment by Dannyzen** [comment]
@mfeltscher Thanks for submitting an issue. I'll restate the problem so the issue is clear: There are two versions being stated. The first in `.bp-config/options.json` and the second in `composer.json`. 
Currently, we prioritize `composer.json`. 
What prevents you from modifying `composer.json` to support your intended version?

**Comment by mfeltscher** [comment]
@Dannyzen Exactely. I don't want to change my `composer.json` since the app is fully functional in PHP 5.5, 5.6 and 7 and therefore `composer.json` should reflect this. There are lots of people working with this app and they are allowed to use PHP 5.5 for development.
I still don't get why you prioritize `composer.json` over the version in `options.json` in such a way.

**Comment by Dannyzen** [comment]
You make a good point that this not entirely expected behavior. With regards to your proposed change, we're concerned it would break existing setups. However, I have put a story into our backlog to notify users that versions conflict (credit to @dmikusa-pivotal for the idea). We'll need to do some additional work in the long-term to make the conflict resolution seamless. For now, I'd suggest removing the versioning in `composer.json` to work around the issue.

**Comment by mfeltscher** [comment]
Sounds good, thanks!
I found a different temporary solution for my problem: According to https://getcomposer.org/doc/04-schema.md#package-links you can use the [caret syntax](https://getcomposer.org/doc/articles/versions.md#caret) to specify PHP versions so I changed my `composer.json` accordingly:
```
...
    "require": {
        "php" : "^5.5 || ^7.0",
...
```

Since this is not getting parsed by your implementation the buildpack falls back to the setting used in `options.json` and everything works as expected.

**Comment by Dannyzen** [comment]
We've completed a story to support a warning message when the `options.json` and `composer.json` conflict. 

Thanks again for bringing this issue to our attention
