### ISSUE TITLE
HTTP_PROXY propagation from cf push env

### ISSUE THREAD

**Issue by avasseur-pivotal** [cloudfoundry/php-buildpack#145]
What version of Cloud Foundry are you using?
1.6

What version of the buildpack you are using?
4.3.10, 4.3.12, master

If you were attempting to accomplish a task, what was it you were attempting to do?
cf push phpmyadmin

What did you expect to happen?

What was the actual behavior?
We have HTTP_PROXY in manifest.yml / env - or in cf ssevg
The variable is not propagated to PHP BP options.json - so we also need to manually set it into it.
That would be useful to propagate it if one is found during the BP staging process into the options.json 

Please confirm where necessary:
* [ ] I have included a log output 
* [ ] My log includes an error message 
* [ ] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
>We have HTTP_PROXY in manifest.yml / env - or in cf ssevg
>The variable is not propagated to PHP BP options.json - so we also need to manually set it into it.
>That would be useful to propagate it if one is found during the BP staging process into the options.json

Nothing changes or should change the options.json file.  That file and others are loaded and merged into the configuration context of the build pack (i.e. it's running state).  The build pack pulls it's config from the context.  

The [environment variables](https://github.com/cloudfoundry/php-buildpack/blob/master/lib/build_pack_utils/cloudfoundry.py#L34-L35) should also be loaded into the context. Because everything is loaded into the context, I don't think it should really matter if you set the proxy in options.json or as environment variables.  That is the intent at least.  It's possible there's a bug here.

Can you give some more details?  The full output of staging with BP_DEBUG enabled would be the most help.  Also, what specifically is failing to use the proxy?  The build pack configures proxy support for Python, thus any Python that makes HTTP requests should use the proxy settings.  There are other things that run during the build pack staging though and it may be one of those that is not accepting the proxy settings.  More details there would help to understand the problem.

Thanks!

**Comment by sesmith177** [comment]
@avasseur-pivotal is this still an issue?

**Comment by avasseur-pivotal** [comment]
Customer reported only lower case http_proxy worked. I can t test it short term but can ask extra confirmation later

Envoyé de mon iPhone

**Comment by Dannyzen** [comment]
@avasseur-pivotal any update here?

**Comment by geramirez** [comment]
Bump. Just checking in to see if this issue has been resolved.

**Comment by avasseur-pivotal** [comment]
I don't have platform to test this anymore - but got confirmation that only lowercase http_proxy env var name in manifest.yml worked.
Closing.
