### ISSUE TITLE
As a PHP developer, I want to be able to safely use PHP modules of my choice

### ISSUE THREAD

**Issue by jchesterpivotal** [cloudfoundry/php-buildpack#162]
In https://github.com/cloudfoundry/php-buildpack/issues/160 and https://github.com/cloudfoundry/php-buildpack/pull/161, we discussed a PR to allow developers to submit arbitrary modules to be mounted up at runtime.

The buildpacks team rejected the PR, but recognise that there is still an unfilled need in search of a solution.

We think that any proposed solution needs:
1. To respect the operator contract -- if developers use this function, I am confident that their selected modules are kept up-to-date
2. To require minimal effort from developers -- I don't want to have to learn how to use binary-builder

We don't want to prejudge any possibilities, so we're opening up this issue for further discussion.

**Comment by sclevine** [comment]
One solution would be to allow apps to vendor PHP extension source code. The buildpack could compile that source code during staging. This would be similar to how native extensions work in the Ruby buildpack.

Advantages over allowing pre-compiled extensions:
- Easier for developers than compiling PHP extensions against a Dockerized version of the rootfs
- Less risky, because we avoid the situation where developers upload PHP extensions that are statically linked to vulnerable libraries from older versions of the rootfs
- More transparent, because the developer knows exactly what source code is going into their app

Advantages in general:
- Could be extended to pull the latest source code for the needed extensions from PECL

Disadvantages:
- Nothing would prevent developers from vendoring old PHP extensions that have security vulnerabilities
- Compile-time dependencies of PHP extensions may not be present in the rootfs

(This was originally suggested by @flavorjones)

**Comment by jchesterpivotal** [comment]
Agreed that it leaves the possibility of dated extensions being uploaded. We do face this with other source-vendoring buildpacks, though, so it wouldn't necessarily lower our current threshold.

**Comment by sesmith177** [comment]
@sdeeg-pivotal did you have any thoughts on this?

**Comment by keaty** [comment]
Investigation prioritized at https://www.pivotaltracker.com/story/show/129371609

**Comment by Zanadar** [comment]
Closing as way stale
