### ISSUE TITLE
Creating a file in /etc/cron.hourly

### ISSUE THREAD

**Issue by ghost** [cloudfoundry/php-buildpack#17]
Hi,

I've noticed when running my application that the /etc/cron... entries exist, which suggests there is an active cron available to my application...

Can you tell me how I would make a file be stored in /etc/cron.hourly (for example) when I do my `cf push APP`? (or is this something the buildpack doesn't support?)

**Comment by ajitrishabh** [comment]
@dmikusa-pivotal can you please guide how exactly i can run cron job in my application.
this for MindSphere (if you know)
im really stuck with this how i can run some code every day.

**Comment by dmikusa-pivotal** [comment]
There is no cron on Cloud Foundry. For cron to work, there's a daemon that must run and that does not run on CF.

With PHP, you have a few of choices:

 - you can have an external scheduling service send you HTTP requests to a specific endpoint on some interval. For example, if you want something to run daily, you could have the service call `https://your-cool-app.example.com/app/cron/daily`. That endpoint would need to run and handle your task. I can't endorse a specific company or service that does this, but they are out there if you search.

 - you can use one of the libraries mentioned in this [SO question](http://stackoverflow.com/questions/190561/what-is-the-best-method-for-scheduled-tasks-in-php). I can't endorse any of them.

 - you can run a PHP script that loops, running your task then sleeping for some period of time and repeats over & over. You can run this as an application on CF.

**Comment by ajitrishabh** [comment]
@dmikusa-pivotal ,
Thanks for the reply.

- i can not do this becoz when i call the endpoint my application session is already expired. so it will send me to the login page.

-  this is all 3rd party which currently i can not use

- if you can help on this part how i can loop my code at particular time when app is not open by any user.

this is very much need to run some calculation and send mail as per result. without user intervention.

**Comment by ajitrishabh** [comment]
@dmikusa-pivotal 
can i execute below command in **ADDITIONAL_PREPROCESS_CMDS** variable of options.json?

*** * * * * cd /path/to/project && php jobby.php 1>> /dev/null 2>&1**

**Comment by dmikusa-pivotal** [comment]
Sorry for the delay. If you want to run `php jobby.php 1` as an app, you can do the following.

1. Add this script to your app.

```bash
#!/bin/bash

while [ 1 -eq 1 ]; do
    php jobby.php 1
    sleep 1
done
```

and adjust `sleep 1` to be the amount of time to wait before the job runs again.

2. Do a `cf push -c 'loop.sh'` where `loop.sh` is the name of the script from #1.

This should push your app, run the script which loops and runs your job repeatedly.

-------

Another option would be to use PCF Scheduler. This allows you to easily schedule jobs to run. I believe it even has cron-like syntax for scheduling durations. It is proprietary though and only available if you're running Pivotal Cloud Foundry or using Pivotal Web Services.

**Comment by ajitrishabh** [comment]
@dmikusa-pivotal 
Thanks for the reply.
1. Add this script to your app. ---->**where to add this script in my app? do i need to create loop.sh in my htdocs folder and in loop.sh i whould update the script given by you.**
2. Do a cf push -c 'loop.sh' where loop.sh is the name of the script from #1. ----> **you mean script from point 1 or from the link given by you (if so i could not find any script in the link provided)**

i really need to do this scheduler thing for my project otherwise i have to re-code  everything in Nodejs or may be in Python.

**Comment by dmikusa-pivotal** [comment]
>where to add this script in my app? do i need to create loop.sh in my htdocs folder and in loop.sh i whould update the script given by you.

It can go anywhere. I would put it either in the root, or maybe in a folder called `scripts`. You probably don't want it under `htdocs` otherwise it would be possible for someone that new the path to download that remotely (everything under `htdocs` is public, unless you block it with an `htaccess` file).

>you mean script from point 1 or from the link given by you (if so i could not find any script in the link provided)

Sorry, I mean my first bullet. Github like to turn anything prefixed with a pound sign into a link to a Github issue. That's not what I meant.

So if you put the `loop.sh` script in the root of your project you can run `cf push -c 'loop.sh'`. If you put it in a scripts subfolder, you can run `cf push -c 'scripts/loop.sh'`. The `-c` argument just needs a path relative to the root of your project where it should find the script to run.

HTH

**Comment by ajitrishabh** [comment]
it is not working.  getting below error.

```
-  2019-04-11T09:33:06.96+0530 [CELL/0] ERR Failed to make TCP connection to port 8080: connection refused
-    2019-04-11T09:33:06.96+0530 [CELL/0] ERR Timed out after 1m0s: health check never passed.
-    2019-04-11T09:33:07.88+0530 [APP/PROC/WEB/0] OUT Exit status 143
-    2019-04-11T09:33:08.16+0530 [CELL/0] OUT Cell c5bb5604-816d-44a7-a406-7d215addaa2a stopping instance 7d2886a9-f32b-4889-7f21-4924
-    2019-04-11T09:33:08.16+0530 [CELL/0] OUT Cell c5bb5604-816d-44a7-a406-7d215addaa2a destroying container for instance 7d2886a9-f32b-4889-7f21-4924
-    2019-04-11T09:33:08.55+0530 [CELL/0] OUT Cell c5bb5604-816d-44a7-a406-7d215addaa2a successfully destroyed container for instance 7d2886a9-f32b-4889-7f21-4924
-    2019-04-11T09:34:32.68+0530 [CELL/0] OUT Cell 0a1b49d0-624b-48db-b63c-1e572b9a1bbe creating container for instance 6a134a14-90b3-43fa-72b2-8fde
-    2019-04-11T09:34:33.07+0530 [CELL/0] OUT Cell 0a1b49d0-624b-48db-b63c-1e572b9a1bbe successfully created container for instance 6a134a14-90b3-43fa-72b2-8fde
-    2019-04-11T09:34:37.19+0530 [CELL/0] OUT Starting health monitoring of container
```
**cf version 6.40.0+07673feb9.2018-10-08**
Manifest file:

- Updating app with these attributes...
-   name:                phpTestingApp
-   path:                C:\xampp\htdocs\mindsphere\cfphpapp\phpTestingApp_cron
-   command:             'script/loop.sh'
-   disk quota:          512M
-   health check type:   port
-   instances:           1
-   memory:              128M
-   stack:               cflinuxfs3

need your expertise if you can provide some sample build pack which i can test directly.

what i am doing with `loop.sh`  is creating text file and adding some text in that file so that i can see this text file is updating or not by doing `ssh`

**Comment by ajitrishabh** [comment]
Hi @dmikusa-pivotal ,

not able to run sh script in my app as you suggested here [https://github.com/cloudfoundry/php-buildpack/issues/17#issuecomment-479480188](url)

need help here.
1. i used this **ADDITIONAL_PREPROCESS_CMDS** not working
2. did `cf push -c 'loop.sh'` not working 
2. created **Procfile** file still not working 

if you can provide sample app to test at my end it would great.


![image](https://user-images.githubusercontent.com/7721618/87244691-9e4b6d00-c45c-11ea-85e6-23a3780264b1.png)


```
Updating app with these attributes...
  name:                phptestingcron
  path:                C:\xampp\htdocs\mindsphere\cfphpapp\php_cf_cron
  command:             loop.sh
  disk quota:          512M
  health check type:   port
  instances:           1
  memory:              128M
  stack:               cflinuxfs3
  routes:
    phptestingcron.apps.eu1.mindsphere.io
```

**2020-07-12T16:18:50.80+0530 [APP/PROC/WEB/0] ERR bash: loop.sh: command not found**
```
 2020-07-12T16:18:50.79+0530 [APP/PROC/WEB/0] OUT Could not open input file: ../htdocs/testing.php
   2020-07-12T16:18:50.80+0530 [APP/PROC/WEB/0] ERR bash: loop.sh: command not found
   2020-07-12T16:18:50.84+0530 [APP/PROC/WEB/0] OUT Exit status 127
   2020-07-12T16:18:50.84+0530 [CELL/SSHD/0] OUT Exit status 0
   2020-07-12T16:18:57.53+0530 [CELL/0] OUT Cell a3ffc01d-afd8-4193-9493-e56c1c95de1f stopping instance 34ab241a-4973-42da-723e-281a
   2020-07-12T16:18:57.53+0530 [CELL/0] OUT Cell a3ffc01d-afd8-4193-9493-e56c1c95de1f destroying container for instance 34ab241a-4973-42da-723e-281a
   2020-07-12T16:18:57.55+0530 [API/1] OUT Process has crashed with type: "web"
   2020-07-12T16:18:57.60+0530 [API/1] OUT App instance exited with guid 23969abf-8f95-4ce2-a8db-4d965725b07f payload: {"instance"=>"34ab241a-4973-42da-723e-281a", "index"=>0, "cell_id"=>"a3ffc01d-afd8-4193-9493-e56c1c95de1f", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 127", "crash_count"=>3, "crash_timestamp"=>1594550937498536096, "version"=>"213097ef-3c7a-4782-ada1-453fcf0fa1a1"}
   2020-07-12T16:18:57.77+0530 [PROXY/0] OUT Exit status 137
   2020-07-12T16:18:58.04+0530 [CELL/0] OUT Cell a3ffc01d-afd8-4193-9493-e56c1c95de1f successfully destroyed container for instance 34ab241a-4973-42da-723e-281a
```
