### ISSUE TITLE
php-buildpack should not complain about compiled in modules

### ISSUE THREAD

**Issue by giner** [cloudfoundry/php-buildpack#180]
If a compiled in module is included in PHP_EXTENSIONS then the buildpack is saying `The extension '...' is not provided by this buildpack.` at the staging process. While this does not harm it is still very confusing as it sounds as if there was no support for the module at all.

```
$ cat php-7.0/.bp-config/options.json
{
    "PHP_VERSION": "{PHP_70_LATEST}",
    "PHP_EXTENSIONS": ["libxml","sqlite3","test"]
}

$ cf push php-extensions-70-test -p php-7.0 -b https://github.com/cloudfoundry/php-buildpack.git
...
Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php7/php7-7.0.13-linux-x64-1479850467.tgz] to [/tmp]
The extension 'libxml' is not provided by this buildpack.
The extension 'sqlite3' is not provided by this buildpack.
The extension 'test' is not provided by this buildpack.
...
```

The list of compiled in modules can be get by running `php -m` or by php code `print_r(get_loaded_extensions());`. Here is an example list for php 7.0 from the latest php-buildpack:
```
Core
date
libxml
pcre
sqlite3
bcmath
calendar
ctype
dom
filter
hash
iconv
intl
json
SPL
posix
readline
Reflection
session
SimpleXML
standard
Phar
tokenizer
xml
xmlreader
xmlwriter
mysqlnd
cgi-fcgi
```

It would be nice to make this message more meaningful (something like "this module is compiled in") for compiled in modules.

**Comment by RochesterinNYC** [comment]
@giner so if we're understanding this correctly, the `The extension '...' is not provided by this buildpack` message is printed when an extension you specify in the `PHP_EXTENSIONS` section of your `options.json` is not in the list of additional extensions that we build into our PHP binaries.

However, this message is also printed when you specify extensions that are natively built into PHP by default and that are actually available ? And this is confusing because the outputted message leads one to believe that the extensions are not available when they ultimately are and the app stages correctly using those available extensions.

If so, I agree with the need for a better error message and better logic around when the error message is printed.

I think that if a system or additional extension is specified that's available, no additional output should be produced. If an additional or system extension is specified that is not available, an output message like `The extension '...' is not compiled into the PHP #.#.# in this buildpack.`

**Comment by flavorjones** [comment]
@RochesterinNYC At one point I think we had logic that omitted this warning message if the extension was built into PHP ... This may be a regression if I'm remembering correctly. It may be worth looking at changes to this code over the past year.

**Comment by RochesterinNYC** [comment]
@flavorjones Hm, do you recall around what time this logic was intact? It looks like the logic around warning about extensions hasn't changed since its [original conception](https://github.com/cloudfoundry/php-buildpack/commit/356a4737674d0be2b5b5270d6e66bc8aa25c5b2e).

**Comment by giner** [comment]
> so if we're understanding this correctly, the The extension '...' is not provided by this buildpack message is printed when an extension you specify in the PHP_EXTENSIONS section of your options.json is not in the list of additional extensions that we build into our PHP binaries.
>
> However, this message is also printed when you specify extensions that are natively built into PHP by default and that are actually available ? And this is confusing because the outputted message leads one to believe that the extensions are not available when they ultimately are and the app stages correctly using those available extensions.

Correct

> I think that if a system or additional extension is specified that's available, no additional output should be produced

Sounds good. It is probably make sense to add the list of compiled in modules to the release notes. 

> If an additional or system extension is specified that is not available, an output message like The extension '...' is not compiled into the PHP #.#.# in this buildpack.

"Complied into" could be confusing though because some modules are put there as extensions, while others are compiled in. The original message should be ok as long as it is not shown for extensions which are actually compiled in.

**Comment by dmikusa-pivotal** [comment]
Some context on this.  When you build the PHP binary (binary-builder), you essentially pick what is statically built into PHP and what is built as a shared library.  Things statically built into PHP don't have an extension, they just exist.  Things built as a shared library have an extension that must be loaded.  

I'm not sure there's a "standard" set of what's built-in vs built as an extension.  In some Linux distro's there's very little (maybe even nothing) built in statically and everything is an extension.  That's why things like composer don't assume even trivial things like date or dom or json are there (composer is the #1 way I've seen the messages reported in this issue).  With other binary distros, you'll get some base level with not so common functionality built as shared extensions.

If I could go back and do it again, I would take the approach of building in nothing (or as little as possible) and producing more shared libraries instead.  It seems cleaner and seems like what is most commonly done by distros.  To this point, I haven't suggested it as there didn't seem to be any benefit, however making some changes to build everything (or as much as possible) as an extension would be one way to resolve this issue, so perhaps it's something to consider.

**Comment by athornton2012** [comment]
@dmikusa-pivotal So that would entail not building in all of the modules like sqlite directly into PHP but including it as a shared library that's located inside the end PHP tarball ? (ex. under the `lib/php/extensions/no-debug-non-zts-20151012` directory). 

And this would entail not building it with a lot of these configuration flags: https://github.com/cloudfoundry/binary-builder/blob/master/recipe/php7_meal.rb#L9-L50 ?

**Comment by dmikusa-pivotal** [comment]
@athornton2012 - Yes.  That's correct.  I'm not sure why, but some of the PHP extensions can be built as shared libraries by setting `--with-xxxx=shared` or `--enable-xxxx=shared` in the `./configure` script ([example](https://github.com/cloudfoundry/binary-builder/blob/master/recipe/php7_meal.rb#L19).  Other's don't seem to like that and will ignore attempts to tell them to build as shared, which leaves them as being built into the PHP binary ([example](https://github.com/cloudfoundry/binary-builder/blob/master/recipe/php7_meal.rb#L13).

For the ones that do not, what you can do is to disable them.  This should make sure that they are not included in statically into the PHP binary.  Then you can build them manually like is being done with the [Oracle PDO extension](https://github.com/cloudfoundry/binary-builder/blob/master/recipe/php_common.rb#L175-L197).

Hope that helps!

**Comment by keaty** [comment]
Hey @dmikusa-pivotal, that sounds like something we should investigate changing. @sclevine, thoughts?

**Comment by sclevine** [comment]
Converted this story to an investigative story: https://www.pivotaltracker.com/story/show/135499949

If we determine that it isn't worth it to convert the built-in extensions to shared libraries, I'll file a story to improve the warning logic for built-in extensions.

**Comment by sclevine** [comment]
Fix shipped in the latest version of the buildpack.
