### ISSUE TITLE
As a devops, I want to be able to make some changes to php.ini file to suit the application

### ISSUE THREAD

**Issue by liaogz82** [cloudfoundry/php-buildpack#197]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

{
   "name": "",
   "build": "",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.system.vpcf-qa.in.spdigital.io",
   "token_endpoint": "https://uaa.system.vpcf-qa.in.spdigital.io",
   "min_cli_version": "6.7.0",
   "min_recommended_cli_version": "6.11.2",
   "api_version": "2.58.0",
   "app_ssh_endpoint": "ssh.system.vpcf-qa.in.spdigital.io:2222",
   "app_ssh_host_key_fingerprint": "95:00:ce:6f:83:d7:8b:d2:71:8b:cd:a6:7d:d3:d4:c8",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.system.vpcf-qa.in.spdigital.io/routing",
   "logging_endpoint": "wss://loggregator.system.vpcf-qa.in.spdigital.io:443",
   "doppler_logging_endpoint": "wss://doppler.system.vpcf-qa.in.spdigital.io:443",
   "user": "9de0451f-96a9-4a61-8963-e60e712c55d9"
}
cf version 6.23.0+c7866be18-2016-12-22

What version of the buildpack you are using?
v4.3.28

If you were attempting to accomplish a task, what was it you were attempting to do?
Deploying Piwik

What did you expect to happen?
Able to deploy piwik

What was the actual behavior?
<img width="892" alt="screen shot 2017-03-02 at 4 56 58 pm" src="https://cloud.githubusercontent.com/assets/317035/23501004/283c53b6-ff6d-11e6-82a8-b322264661e5.png">

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by liaogz82** [comment]
I am unable to change the `php.ini` file to enable a proper deployment of piwik. Please help

Right now I just fork the repository and remove the commented setting in the php.ini

**Comment by dmikusa-pivotal** [comment]
You have some options:

1.) Drop in a `.user.ini` file. [Instructions](https://secure.php.net/manual/en/configuration.file.per-user.php)
2.) Drop in a `.htaccess`.  Assuming you're using HTTPD, you can use this to override `php.ini` settings.
3.) Override the entire `php.ini` file.  [Instructions](https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#engine-configurations).  If you go this route, start by downloading the `php.ini` file from the build pack for [your version of PHP](https://github.com/cloudfoundry/php-buildpack/tree/master/defaults/config/php).  You cannot use an out-of-the-box `php.ini` because there are things we customize to make the build pack work.

I would suggest #1 or #2.  The third option should really only be used as a last resort.

**Comment by sclevine** [comment]
Closing this as the question has been addressed.
