### ISSUE TITLE
Checksum of downloaded dependency does not match expected value

### ISSUE THREAD

**Issue by JohannesRudolph** [cloudfoundry/php-buildpack#262]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
[jrudolph@localhost dev]$ cf curl /v2/info && cf version
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.cf.eu-de-darz.msh.host",
   "token_endpoint": "https://uaa.cf.eu-de-darz.msh.host",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.103.0",
   "app_ssh_endpoint": "ssh.cf.eu-de-darz.msh.host:2222",
   "app_ssh_host_key_fingerprint": "ff:67:ef:07:6e:37:0c:a7:67:c5:6c:02:dd:b5:c1:16",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.cf.eu-de-darz.msh.host:443",
   "routing_endpoint": "https://api.cf.eu-de-darz.msh.host/routing"
}
cf version 6.36.1+e3799ad7e.2018-04-04
``` 

What version of the buildpack you are using?
latest (v4.3.52 at time of writing)

If you were attempting to accomplish a task, what was it you were attempting to do?
cf push an app that uses PHP_71_LATEST

What did you expect to happen?
a working build.

What was the actual behavior?
The build fails intermittently, sometimes it passes, sometimes it fails with the following error:

```
Staging app and tracing logs...
  Creating container
  Successfully created container
  Downloading app package...
  Downloaded app package (125.6M)
  -------> Buildpack version 4.3.52
  Installing HTTPD
  HTTPD 2.4.29
  Downloaded [https://buildpacks.cloudfoundry.org/dependencies/httpd/httpd-2.4.29-linux-x64-689e1bd2.tgz] to [/tmp]
  Installing PHP
  PHP 7.1.16
  Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php7/php7-7.1.16-linux-x64-0943fdaf.tgz] to [/tmp]
  Traceback (most recent call last):
    File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/scripts/compile.py", line 59, in <module>
      .from_build_pack('lib/additional_commands')
    File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/build_pack_utils/builder.py", line 209, in extensions
      process_extension(path, ctx, 'compile', process, args=[self])
    File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/build_pack_utils/utils.py", line 69, in process_extension
      success(getattr(extn, to_call)(*args))
    File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/extensions/composer/extension.py", line 449, in compile
      return composer.compile(install)
    File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/extension_helpers.py", line 154, in compile
      self._compile(install)
    File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/extensions/composer/extension.py", line 200, in _compile
      self.install()
    File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/extensions/composer/extension.py", line 222, in install
      self._builder.install().package('PHP').done()
    File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/build_pack_utils/builder.py", line 185, in package
      self._installer.install_binary(key)
    File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/build_pack_utils/cloudfoundry.py", line 214, in install_binary
      strip=strip)
    File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/build_pack_utils/cloudfoundry.py", line 190, in _install_binary_from_manifest
      self._dwn.download(url, self._ctx['TMPDIR'])
    File "/tmp/buildpackdownloads/3f0c03c7602ee67512337b56bc424f4b/lib/build_pack_utils/downloads.py", line 40, in download
      raise RuntimeError("Checksum of downloaded dependency does not match expected value")
  RuntimeError: Checksum of downloaded dependency does not match expected value
  Failed to compile droplet: Failed to run finalize script: exit status 1
  Exit status 223
Error staging application: App staging failed in the buildpack compile phase
FAILED
ERROR: Job failed: exit code 1
``` 

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
Is your lab/environment able to talk to the Internet?  Is it behind a proxy?  

It appears that the buildpack is reaching out to try and download files from the Internet.  The file downloaded does not match the hash, which implies a problem downloading the file, so the buildpack fails.  

I asked the question above because this could happen if you're Internet access is restricted.  Maybe you're getting redirected or being presented some captive portal-like page telling you to use proxy?

If you need to use a proxy to access the internet, you can configure that here: https://docs.cloudfoundry.org/buildpacks/php/index.html#proxy_support

The other option is to use a cached/offline version of the buildpack.  This won't need to access the internet.  You'll know when you're using this because the downloads will look different.

Ex:  `Downloaded [file:///tmp/buildpacks/c211bd5b52c2898a11559a732dfb84ed/dependencies/https___buildpacks.cloudfoundry.org_dependencies_httpd_httpd-2.4.29-linux-x64-689e1bd2.tgz] to [/tmp]`

We do not distribute cached/offline versions of buildpacks anymore, due to distribution/licensing problems, but you can build your own using the instructions here:  https://github.com/cloudfoundry/php-buildpack#building-the-buildpack

**Comment by JohannesRudolph** [comment]
Hi, this is in a public cloud with unconstrained access to the internet during staging - hence my question what could possibly lead to this error (CDN inconsistencies and whatnot)? 

The issue hasn't resurfaced so far, so I'm happy to close this as it's very likely difficult to reproduce. However, at least it's google-able now, so fellow CF operators and users can chime in if they notice a similar issue.
