### ISSUE TITLE
Commercial Licenses Required for extensions?

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/php-buildpack#278]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
CFD 1.19

What version of the buildpack you are using?
4.3.51

Our legal department had a question about including 2 agents with commercial licenses.

The buildpack includes as "extensions" ..
appdynamics-php-agent-x64-linux-4.3.5.9
CA-APM-PHPAgent-10.6.0_linux

These both require commercial licenses to use past a 30 day trial period.  Can you explain why and how these are added and how this might effect the license of the php-buildpack

**Comment by dmikusa-pivotal** [comment]
I'm not a lawyer, so I can only answer technical questions.

The buildpack does not actually include those agents. The buildpack includes code, which was written specifically for the buildpack, that allows you to install those agents. You, the user, need to make the actual binaries available to the buildpack so that it can download and install them.

My understanding is that this is a common way for OSS to integrate with proprietary software, and that this is similar to how PHP supports Oracle. There are Oracle extensions, the extensions are OSS, but they don't work unless you install the Oracle binaries, which are not distributed by PHP.

**Comment by ameyer-pivotal** [comment]
@andrew-edgar I'll go ahead and close this, as I believe it was asked/answered on Slack (https://cloudfoundry.slack.com/archives/C02HWMDUQ/p1536062295000100).
