### ISSUE TITLE
stack missing

### ISSUE THREAD

**Issue by segunmicheal27** [cloudfoundry/php-buildpack#297]
when i run cf stacks i cannot find cflinuxfs3 according to the php7 we find out its cflinuxfs3 has php 7.3.3. So how can i upgrade stack

**Comment by dmikusa-pivotal** [comment]
Stacks are not supplied by a build pack. They are made available by your platform operator. If you run `cf stacks` and do not see `cflinuxfs3` then you need to contact your platform operator and ask they to deploy `cflinuxfs3`. 

They should be very motivated to do this ASAP because `cflinuxfs2` is based on Ubuntu Trusty which officially goes out of support this month (i.e. no more security fixes).

https://wiki.ubuntu.com/Releases

You will also need `cflinuxfs3` in order to use newer versions of PHP 7, like 7.3. These versions need the newer versions of dependencies that are only provided in `cflinuxfs3`.

**Comment by Zanadar** [comment]
Closing.
