### ISSUE TITLE
HHVM Updates

### ISSUE THREAD

**Issue by croemmich** [cloudfoundry/php-buildpack#30]
I'd love to use HHVM rather than FPM but the included version of HHVM is too unstable. Any chance of getting 3.3 or 3.4? I'm not sure how to go about creating the binaries. I may be able to do it if you can point me in roughly the right direction.

**Comment by chregu** [comment]
I made a binary for the buildpack with HHVM-3.5.0, have to publish how I did it soon somewhere.

**Comment by dmikusa-pivotal** [comment]
Nice!  Would be interested in seeing that.  Let me know if you get some instructions together.

**Comment by chregu** [comment]
Here's what I did (using docker for compilation)
https://github.com/chregu/cf-update-hhvm-for-php-build-pack
Worked for me, but it's not totally automated.

(be aware that I used a patched HHVM for my needs, just adjust build/hhvm.sh and Dockerfile to use the official sources)

**Comment by dmikusa-pivotal** [comment]
An update on this.  

1.) If you use the trusty based stack in CF v201+, you can get HHVM 3.5.0.  I also just saw that HHVM 3.6.0 is out now.  I will add support for that on trusty shortly.  If you have any problems using those versions, open a new issue and we'll take a look there.

2.) Since trusty is the future and lucid will go away at some point (hopefully soon), I'd say it's a safe bet that the lucid stack won't ever see anything beyond HHVM 3.2.0.  Given this and that we have support for newer versions of HHVM on trusty, I'm going to close out this issue.

Dan
