### ISSUE TITLE
Build pack error 

### ISSUE THREAD

**Issue by saumildharia** [cloudfoundry/php-buildpack#31]
Hi 
I am getting the following error while using this build pack to host a web application 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 28: ordinal not in range(128) 2014-12-11T00:09:41.05-0800 [API] ERR Encountered error: App staging failed in the buildpack compile phase.
I believe this is due to the font files which are used by the web application  are unable to compile by the php build pack Can you advise how this could be solved?

**Comment by squeedee** [comment]
@dmikusa-pivotal can you link to a backlog story for this issue?

**Comment by dmikusa-pivotal** [comment]
This came in prior to setting up the gitbots.  I don't think there's a story for it.

**Comment by dmikusa-pivotal** [comment]
I did some testing with this and was able to recreate a similar problem.  It happens when there's a file with a non-ascii character in the name, which has the replace function called on it and one of the arguments to replace is a unicode string.  This causes an automatic decode on the file name, which fails because it has a non-ascii character.

The best fix seems to be [this one](https://github.com/cloudfoundry/php-buildpack/blob/master/lib/build_pack_utils/builder.py#L594-L595), which makes sure that a unicode string is passed into os.walk.  This makes the values returned by os.walk unicode strings, which eliminates the automatic conversion.

The short story here is I believe this is fixed.  Closing it out.  If it pops back up, just re-open.
