### ISSUE TITLE
Failed to compile a droplet with compile.py if specifying PHP Buildpack as a final buildpack of multiple buildpacks with Python buildpack

### ISSUE THREAD

**Issue by AkihiroKitada** [cloudfoundry/php-buildpack#323]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
- cf version 6.46.0+29d6257f1.2019-07-09

What version of the buildpack you are using?
- PHP Buildpack: v4.3.78
- Python Buildpack: 1.6.36

If you were attempting to accomplish a task, what was it you were attempting to do?
- Trying to push application with multiple buildpacks based on PHP Buildpack and Python Buildpack with the following condition.
-- final buildpack is PHP Buildpack
-- expecting to use Python 3

What did you expect to happen?
- Succeeding to push application with multiple buildpacks based on PHP and Python 3

What was the actual behavior?
- While compiling a droplet, it fails with the following error messages.
```
     File "/tmp/buildpacks/705484ca4631170e6052a2a6cba35309/scripts/compile.py", line 80
       print 'Finished: [%s]' % datetime.now()
                            ^
   SyntaxError: invalid syntax
   Failed to compile droplet: Failed to run finalize script: exit status 1
   Exit status 223
```

- The steps to reproduce the issue is following.
1. Prepare manifest.yml at /path/to/app to push an app with multiple buildpacks based on PHP and Python, which final buildpack is PHP as below.
```
---
applications:
- name: php-and-python
  buildpacks:
  - python_buildpack
  - php_buildpack
```
2. Prepare runtime.txt at /path/to/app to push app with expecting using Python 3 as below.
```
python-3.x
```
3. Prepare index.html as a dummy web app at /path/to/app/htdocs as below.
```
Hello World!
``` 
4. Go to /path/to/app and trigger `cf push`.

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by dmikusa-pivotal** [comment]
What you're saying makes sense. The use of the Python buildpack first is installing Python3. That's what's on the path. That then impacts the PHP buildpack which uses Python2. The script breaks because it's not Python3 compatible.

I think with a little work we could probably make it Python3 compatible, but we'd have to test with Python2 and 3 which complicates things a lot.

For what it's worth, the PHP Cloud Native Buildpacks are written in Golang so this issue will go away (no pun intended).

**Comment by AkihiroKitada** [comment]
Hi @dmikusa-pivotal 

Thank you for your comment. The ideal resolution should be provided via CNB in the future. However, in the reality, Python 2 won't be maintained no later than January, 2020. Until then, this issue should be addressed for multi-buildpack users.  Otherwise, this issue should be fixed in the existing release of buildpacks.

**Comment by dfreilich** [comment]
@AkihiroKitada we'll keep it in mind! I don't think that the work is going to happen immediately (even if Python 2 isn't actively maintained after January 2020, people aren't going to migrate immediately, and forcing people to would cause more issues than it would solve), particularly since our priorities are now focused on CNBs. I'll close it for now, though if you want to PR an update that is compatible for both python 2 and 3, we'd be happy to see that. 

Thanks for the help!
