### ISSUE TITLE
SSH2 PHP library 

### ISSUE THREAD

**Issue by dlorenzomop** [cloudfoundry/php-buildpack#336]
Hello,

What version of the buildpack you are using?  v4.3.82
If you were attempting to accomplish a task, what was it you were attempting to do?

How can I add SSH2 PHP Library ?
I cannot use a standard installation (apt or yum) into the Cloud because I am not SUDO and I cannot do from source or with PECL because it seems the file necessary for "phpize" are deleted.

**Comment by dmikusa-pivotal** [comment]
Related to https://github.com/cloudfoundry/binary-builder/issues/48

**Comment by dmikusa-pivotal** [comment]
I have PR's for this:

https://github.com/cloudfoundry/binary-builder/pull/53
https://github.com/cloudfoundry/buildpacks-ci/pull/65

**Comment by dmikusa-pivotal** [comment]
@dlorenzomop Unfortunately it's not easy to add PHP extensions because they are compiled C code. You can do it, but it's a lot of hoops to jump through. Because of this, we bundle PHP extensions with our distribution of PHP. I have submitted a couple of PRs so that we build and include this extension as well. You'll need to wait for that to clear though our pipelines & a new version of the PHP buildpack to ship, but after that it should just be available for use.

Hope that helps!

**Comment by dmikusa-pivotal** [comment]
@dlorenzomop it looks like this is in PHP buildpack v4.4.10+. It is only in the latest version of each branch though, see the release notes for details.
