### ISSUE TITLE
No environment variables during composer phase?

### ISSUE THREAD

**Issue by chregu** [cloudfoundry/php-buildpack#34]
When 'composer.phar install' is called by the build pack, it looks like the env variables set through manifest.yml are not set, but they are later, when the actual app runs.

Is that on purpose/design? Or a bug/missing feature?

**Comment by dmikusa-pivotal** [comment]
I would say it's done intentionally.  We setup the environment so that when composer runs, it's properly configured for CF.  Since Composer takes a lot of it's setup from env variables, pulling in other environment variables could override this configuration and unintentionally break stuff.  Using a controlled environment allows us to prevent that from happening.  See these [lines where we build the environment](https://github.com/cloudfoundry/php-buildpack/blob/master/extensions/composer/extension.py#L213-L220).

What's your use case for needing to change this through an environment variable in manifest.yml?  Some of [Composer's behaviors](https://github.com/cloudfoundry/php-buildpack/blob/master/docs/composer.md#configuration) can be changed through the `.bp-config/options.json` file.  If there's something you'd like to change that's not exposed this way, I'd rather expose it here than through the manifest.yml file.

Interested to hear your thoughts though.

**Comment by chregu** [comment]
My use case is telling Symfony to use "prod" during warm up and not the default "dev" during that phase. Usually I can change that with setting the environment Variable SYMFONY_ENV=prod, but that doesn't work here and lead to problems due to not installed libraries.

Maybe there's another way to do this?

**Comment by dmikusa-pivotal** [comment]
Sorry, I'm not familiar with Symfony.  Can you describe more what's going on here?  I understand that you're trying to change from dev to prod, I'm just not sure why that would matter when Composer is installing your binaries.  Do you have a sample app that I can use to see this behavior?

**Comment by chregu** [comment]
Here's an example app https://github.com/chregu/cf-symfony-example

When I push that I get:
````
Installing Nginx
Installing PHP
PHP 5.5.20
Loading composer repositories with package information
Installing dependencies from lock file
  - Removing sensio/generator-bundle (v2.5.1)
Generating autoload files
Updating the "app/config/parameters.yml" file
PHP Fatal error:  Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /tmp/staged/app/app/AppKernel.php on line 33
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command.
```

because I assume composer is run with --no-dev, so the SensioGeneratorBundle is removed, but symfony runs some post-install scripts and then tries to load that in app/AppKernel.php, because it thinks it's in the dev environment.

**Comment by dmikusa-pivotal** [comment]
I think there are a couple options here that should work as things are now.

1.) You can change `COMPOSER_INSTALL_OPTIONS` and remove the `--no-dev` option.  This should keep the SensioGeneratorBundle installed and your scripts should run OK.

2.) You can add the `--no-scripts` option to `COMPOSER_INSTALL_OPTIONS` which will prevent your scripts from running after the install in the staging environment.  If you need those scripts to run, you can then configure them to execute in the runtime environment before your application starts by adding them to the `ADDITIONAL_PREPROCESS_CMDS`.

I can also look at allowing user defined environment variables.  This will take a code change and the trick would be filtering or overlaying them so that they don't inadvertently break things with the build pack.  I'll keep this open as a place holder.

**Comment by chregu** [comment]
Thanks, thought about Option 2) as well. Not a big Fan of Option 1), since that would download/install unnecessary things on each "cf push"

About changing things in your code: It was just a little bit confusing that the env variables are not defined at that stage and took me to figure out some time, why I get that error. Maybe documenting it somewhere (if it's not already is) would help.

Feel free to close this issue

**Comment by chregu** [comment]
mmmh, when I set 

`"COMPOSER_INSTALL_OPTIONS": "--no-scripts"`

also when I set it to

`"COMPOSER_INSTALL_OPTIONS": "--no-interaction --no-dev --no-progress --no-scripts"``

or the default one

`"COMPOSER_INSTALL_OPTIONS": "--no-interaction --no-dev --no-progress"`

, I get:

````
  [RuntimeException]
  Too many arguments.
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
````

--no-interaction doesn't appear in the list, but even if I remove that, it doesn't work

(it all works locally, even when I add the same option twice)

**Comment by chregu** [comment]
Looking at the sources helps. It has to be

`"COMPOSER_INSTALL_OPTIONS": ["--no-scripts", "--no-dev"]`

and everything works fine

**Comment by dmikusa-pivotal** [comment]
Yes, that's correct.  It needs to be a list.  Sorry for the confusion.

**Comment by chregu** [comment]
Just for the record and other people maybe reading this:

`````
"COMPOSER_INSTALL_OPTIONS": ["--no-scripts", "--no-dev"],
"ADDITIONAL_PREPROCESS_CMDS": "php $HOME/php/bin/composer.phar install --no-dev --no-progress"
````

is a solution to the problem (if SYMFONY_ENV=prod is set in manifest.yml)

**Comment by dmikusa-pivotal** [comment]
Is it necessary to run "composer install" again?  That seems like extra work and it's something I would prefer for people not to have to do.

Would it be possible to run your [after-install scripts](https://github.com/chregu/cf-symfony-example/blob/master/composer.json#L26-L43) directly?

Like...

```
"ADDITIONAL_PREPROCESS_CMDS": ["app/console ...", "php some/script.php arg1", ...]
```

**Comment by chregu** [comment]
composer install a 2nd time should be pretty fast as all packages are already installed (it took 1.5 seconds). If I call the scripts separately I'd have to maintain that list twice (once in composer.json where they get added automatically and once in options.json). But of course, if speed is of absolute essence, one should just call those scripts

**Comment by chregu** [comment]
There is a way to just start the scripts defined in composer.json

`composer.phar run-script post-install-cmd``

Will adjust my example later

**Comment by dmikusa-pivotal** [comment]
We're going to address the environment variable situation.

**Comment by jchesterpivotal** [comment]
@chregu we've closed this story in Tracker, so I'm closing it here.
