### ISSUE TITLE
Adding PEAR mail module

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry/php-buildpack#39]
I can add PEAR via the PHP_MODULES option of options.json, but it does not include the mail package.

How should I go about adding it? Should I be modifying the php-pear.tgz that is downloaded at staging time or is an extension the appropriate place to handle this?

**Comment by dmikusa-pivotal** [comment]
When you add pear to the PHP_MODULES, that should install everything that comes with the base PHP install.  What would you usually do to install mail?  What commands would you run?

**Comment by dmikusa-pivotal** [comment]
@johnmcteague Haven't heard back from you on this.  Going to close it out.  If it's still an issue, feel free to reopen.

**Comment by johnmcteague** [comment]
Sorry for leaving this so long. The Mail PEAR module is not part of the default PEAR installation.

You would add Mail by running
    pear install Mail-1.2.0

The pear tgz file that is downloaded by the buildpack does not contain Mail. (e.g. https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.4.39/php-pear-5.4.39.tar.gz)

**Comment by dmikusa-pivotal** [comment]
No worries.  A couple comments below.

>The Mail PEAR module is not part of the default PEAR installation.

Correct.  The `php-pear-5.x.xx.tar.gz` binary that is bundled with the build pack just contains the initial pear files.  It's essentially what you get out-of-the-box with a PHP installation from source.  Additional pear modules like Mail would need to be installed manually.

>You would add Mail by running
>pear install Mail-1.2.0

At the moment, the build pack doesn't support an easy way to do this.  It has support for installing the pear files, but it don't have any built-in support for running the `pear` command to install pear modules.

A couple thoughts on doing this:

  - You could use a [custom extension](https://github.com/cloudfoundry/php-buildpack/blob/master/docs/development.md#extensions) for the build pack.  This would allow you to install them at compile time.

  - You could include a `.profile.d` script with the app, which would run before your app starts.  This should be OK if you have a small number of modules to install.  If you have a lot, you might need to increase the timeout for the app to start and listen for connections, as that won't happen until after the `.profile.d` scripts complete.

  - You can use [Composer](https://getcomposer.org) to install them.  Often times Pear modules are also listed in the Composer repositories, so you can install them directly with Composer instead.  If not, you can also [use Composer to install Pear modules](https://getcomposer.org/doc/05-repositories.md#pear), which will pull them from the Pear repo.

I'd suggest the last option (i.e. Composer), but the other options should work too.

**Comment by johnmcteague** [comment]
Thanks, I went with composer and pulled them direct from PEAR repo, one issue I hit was I had to explicitly include vendor/autoload.php in order for Mail to be visible. Is this expected?

**Comment by dmikusa-pivotal** [comment]
How were you doing it before?  

It depends a little as to how your app is structured, but the build pack tries to put the folder where Composer installs your dependencies on the include_path.  In theory this means, you should be able to just include or require your dependency and then use it.  The auto loader should work too though, as I understand it that just pulls everything in at once instead of needing multiple includes.

**Comment by hairmare** [comment]
Composer builds the ``vendor/autoloader.php`` file for exactly that purpose. In it there is a complete autoloader that knowns where to find classes in the vendor subdir.

This is the expected behaviour of composer since it allows for packages to follow either PSR-0 or PSR-4 naming conventions while still keeping some control over how they organize their file structures.

While you can depend on vendor being on the include_path it is probably wiser to only depend on the autoloader being there as it will make sure that composer installed libs will still be found after an update even if they reorganize their src/ folders.

Btw, since vendor is on the buildpacks default include_path the easiest way to load it would be a simple ``require_once 'autoloader.php';``.
