### ISSUE TITLE
Option to disable composer

### ISSUE THREAD

**Issue by bbodenmiller** [cloudfoundry/php-buildpack#442]
I need a way to disable composer from running for a Matomo installation. The workaround given in https://github.com/cloudfoundry/php-buildpack/issues/74#issuecomment-130439058 to exclude `composer.json` and `composer.lock` via `.cfignore` is insuffiecent because Matomo does a file integrity check and expects those files to exist:

![image](https://user-images.githubusercontent.com/1192780/101717308-e7c3d680-3a53-11eb-8a10-bb031f03cdde.png)

cc @dmikusa-pivotal

**Comment by bbodenmiller** [comment]
Attempted workaround that didn't work:

Create `.bp-config/options.json` with content `{"COMPOSER_PATH":"non-existent-folder"}` based on details at https://docs.cloudfoundry.org/buildpacks/php/gsg-php-composer.html

**Comment by menehune23** [comment]
HI @bbodenmiller, thanks for posting. Since our focus has shifted mostly to the newer [Paketo PHP buildpack](https://github.com/paketo-buildpacks/php), we aren't able to prioritize new feature requests for this CF buildpack.

I'll close this issue for now, but if you'd like to reopen this and submit a PR to address your concern, we'd be happy to take a look.
