### ISSUE TITLE
How to add odbc to the buildpack

### ISSUE THREAD

**Issue by tyyko** [cloudfoundry/php-buildpack#49]
Hello all, When I try to connect to a SAP HANA DB, using odbc_connect() I get:
```
 PHP Fatal error:  Call to undefined function odbc_connect() 
```
As I know, odbc is already included in the default php package, so what I am missing? What should I do to get the buildpack work with that connection?

This may be useful:
http://scn.sap.com/community/developer-center/hana/blog/2013/02/07/php-rocks-on-sap-hana-too-linux-version

thank you!

**Comment by dmikusa-pivotal** [comment]
ODBC is a core extension to PHP, so while it's code is included with PHP it's still an extension that can be enabled / disabled.  It's not currently enabled or packaged with the PHP build pack.

It's something we could look into enabling, but it's probably going to be tricky (which is why it's not currently available) because it requires an ODBC implementation like UnixODBC, which is not provided by CF.  This means we'd need to build that and install it as well.

On top of that the build pack would need to provide a way for you to configure the ODBC layer and upload ODBC drivers (we can't provide these unless they are open source).

If you want to give it a try, you can find the scripts we use to build PHP (and other binaries) [here](https://github.com/dmikusa-pivotal/cf-php-buildpack-binary-build-scripts/).  The first step would be to modify the build scripts to compile UnixODBC & the PHP odbc extension.  With binaries available, the next step would likely be to add an [extension to the build pack](https://github.com/cloudfoundry/php-buildpack/blob/master/docs/development.md#extensions).  That could install the binaries, configure ODBC and the PHP odbc extension.

**Comment by tyyko** [comment]
Thanks a lot for your really fast reply! I'll think if is worth to give it a try this way!

**Comment by flavorjones** [comment]
I'm going to close this for now. We've created a story in our Tracker backlog to consider adding ODBC support, but this work is unscheduled at this time:

    https://www.pivotaltracker.com/story/show/90007786

Please let us know if you try to build ODBC support; whether you succeed or not, it's valuable information.

Thanks for using Cloud Foundry!
