### ISSUE TITLE
Dependency Deprecation: nginx 1.18.x

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/php-buildpack#490]
Deprecation date: 2021-05-01
Link: https://nginx.org/

**Comment by TisVictress** [comment]
See comment here: https://github.com/cloudfoundry/php-buildpack/issues/491#issuecomment-853029291

**Comment by TisVictress** [comment]
Reverted [this change](https://github.com/cloudfoundry/staticfile-buildpack/commit/f3124b8a9bb9c32aa4bfcc2960a45a4af1ad11f8) since we should not remove dependencies until an engineering manager issues a 30-day notice.
We should create a new card to issue a 30-day notice for 1.18 and 1.19, which were deprecated May 26, 2021. We should also make changes to include 1.20.x and 1.21.x
