### ISSUE TITLE
Dependency Deprecation: nginx 1.19.x

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/php-buildpack#491]
Deprecation date: 2021-05-01
Link: https://nginx.org/

**Comment by TisVictress** [comment]
The change to remove the deprecated nginx versions 1.18 and 1.19 also removed all future deprecation dates for nginx: https://github.com/cloudfoundry/php-buildpack/commit/9816a71a8eccc3f2785c7a16c930299c4f032b6e

**Comment by TisVictress** [comment]
Reverted [this change](https://github.com/cloudfoundry/php-buildpack/commit/9816a71a8eccc3f2785c7a16c930299c4f032b6e) since we should not remove dependencies until an engineering manager issues a 30-day notice.
We should create a new card to issue a 30-day notice for 1.18 and 1.19, which were deprecated May 26, 2021. We should also make changes to include 1.20.x and 1.21.x
