### ISSUE TITLE
ca.bintray.com appears to be sunset. binaries unavailable

### ISSUE THREAD

**Issue by thelangley** [cloudfoundry/php-buildpack#517]
cf-cli 7.2.0
cf-deployment 16.15
php-buildpack v4.4.43 or prior

We are trying to build an offline/cached buildpack but some of the artifacts are unavailable.

We get the below message.

```
Using buildpack-packager 2.3.21 from https://github.com/cloudfoundry/buildpack-packager (at v2.3.21@098b0cb)
Using bundler 2.1.4
Bundle complete! 1 Gemfile dependency, 12 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Downloading CAAPM version 20.11.0 from: https://ca.bintray.com/apm-agents/CA-APM-PHPAgent-20.11.0_linux.tar.gz
bundler: failed to load command: buildpack-packager (/usr/local/bundle/bin/buildpack-packager)
```

I initially suspected our enterprise proxy but then found the same from my home ordinateur

See for yourself. Try to download https://ca.bintray.com/apm-agents/CA-APM-PHPAgent-20.11.0_linux.tar.gz

**Comment by shaun7pan** [comment]
Having same issue, I got 403 Forbidden when trying download the tarball.

**Comment by jimconner** [comment]
It appears that bintray was shut down on 1st May and won't be coming back again. 

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by ryanmoran** [comment]
With the shutdown of Bintray, it appears that the CA APM agent (now DX APM agent) is no longer publicly available, which makes it quite difficult for us to provide as part of the buildpack. In addition to that, their documentation now appears to show installation of the agent outside of the buildpack itself: https://techdocs.broadcom.com/us/en/ca-enterprise-software/it-operations-management/dx-apm-saas/SaaS/implementing-agents/php-agent/deploy-and-monitor-a-php-application-on-cloud-foundry.html. I tried to make an account so that I could attempt to follow these directions myself, but my account appears to be in some sort of halfway broken state and will not let me login. Can someone with the ability to access the agent download attempt these instructions and update with their experience? Assuming this works as described, we would likely remove CAAPM support from the buildpack itself going forward.

**Comment by ryanmoran** [comment]
It does appear that we can retrieve this agent from https://packages.broadcom.com/artifactory/apm-agents/CA-APM-PHPAgent-20.11.0_linux.tar.gz. Let's update the reference and cut a new release.

**Comment by arjun024** [comment]
https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.44 released with CA APM sourced from the new location. Feel free to reopen the issue if you still have any problem.
