### ISSUE TITLE
Error with {"COMPOSER_VERSION": "latest"}

### ISSUE THREAD

**Issue by narcoticfresh** [cloudfoundry/php-buildpack#56]
Hi guys

I'm having a project relying on a dependency with caret operator (thus unable to use composer-1.0-alpha9). So in #47 the ability was added to specify using the latest composer.

So now I'm having this `options.json`

```json
{
  "ADMIN_EMAIL": "test@test.com",
  "WEB_SERVER": "nginx",
  "PHP_VERSION": "{PHP_55_LATEST}",
  "NGINX_VERSION": "{NGINX_17_LATEST}",
  "COMPOSER_VERSION": "latest",
  "PHP_MODULES": ["cli", "fpm"],
  "PHP_EXTENSIONS": ["bz2", "zlib", "curl", "mcrypt", "mongo", "openssl", "pdo", "pdo_mysql"],
  "WEBDIR": "web",
  "LIBDIR": ".",
  "ZEND_EXTENSIONS": ["xdebug"],
  "ADDITIONAL_PREPROCESS_CMDS": [
    "bash .cf-prestart.sh"
  ]
}
```

If i now push the app, after the extension install it fails with this error:

```
OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/lucid/php/5.5.23/php-cli-5.5.23.tar.gz] to [/tmp/php-cli-5.5.23.tar.gz]
OUT Could not get translated url, exited with: %s DEPENDENCY_MISSING_IN_MANIFEST: https://getcomposer.org/composer.phar
OUT Staging failed: Buildpack compilation step failed
ERR Encountered error: App staging failed in the buildpack compile phase
```

If I remove the `latest` option for composer, the staging succeeds futher, but then obviously fails because of the caret operator as specified in `composer/installed.json`.

Is this a bug somewhere or is something maybe wrong with my push?

Thanks

**Comment by dmikusa-pivotal** [comment]
This problem has popped up elsewhere too (#55) and is a result of some recent changes to the build pack.  

You can work around it by using a slightly older version of the build pack. You can do this with the -b argument to cf push or with the buildpack attribute in your manifest.yml file.

Ex: `buildpack: https://github.com/cloudfoundry/php-buildpack#8c13f5434b2f31ca960d2bca9153df1978258535

The "#8c13f5434b2f31ca960d2bca9153df1978258535" on the end of the build pack URL specifies the last commit before these changes were made.  Once the problem is fixed, just remove the hash part and it'll go back to using master.

**Comment by narcoticfresh** [comment]
OK I see.. that does the trick indeed ;-) We'll wait for a fix then.. Thanks!

**Comment by narcoticfresh** [comment]
If you want you can close this one now and we'll track #55; clear now with the reference..

**Comment by clement360** [comment]
Had the same problem start happening today: 
Could not load package zendframework/zendframework in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^1.0: Invalid version string "^1.0"

even after I added "COMPOSER_VERSION": "latest" to options.json
{
  "PHP_EXTENSIONS": ["bz2", "zlib", "curl", "mcrypt", "mbstring", "mysqli", "mysql", "gd", "zip"],
  "PHP_VERSION": "PHP_55_LATEST",
  "COMPOSER_VENDOR_DIR":"vendor",
  "COMPOSER_VERSION": "latest"
}

I am using v3.0.3 currently

**Comment by dmikusa-pivotal** [comment]
COMPOSER_VERSION latest is not going to work with version v3.0.3.  It was added after that.  Try using v3.1.0 or the specific commit I mentioned above.  Both should have support for Composer version latest.

**Comment by clement360** [comment]
my deployment only seems to work with 3.0.3, would there be a way for me to fork 3.0.3 and update the composer version, as a quick fix. I will definitely have to resolve the issues I have with 3.1.0 though

**Comment by dmikusa-pivotal** [comment]
I would suggest opening a new issue and reporting the problem you're seeing with 3.1.0.  It's probably easier to fix that then try to fork and pull back the changes for composer improvements.

**Comment by jtarchie** [comment]
With the buildpack becoming apart of official `cf-release`, we've had to vendor and lock versions and packages for the PHP buildpack. We have *1.0.0-alpha9* locked because it was the last marked release. The latest snapshot version changes constantly and we cannot lock and pack a specific version easily.

When composer cuts a new release, we are more than happy to add it into the buildpack and cut a new official release.

Thanks.

--jtarchie

**Comment by flavorjones** [comment]
@dmikusa-pivotal or @jtarchie -- am I understanding correctly that this is a regression since 3.1.0 related to the introduction of `compile-extensions`?

**Comment by dmikusa-pivotal** [comment]
@flavorjones - 3.1.0 does support COMPOSER_VERSION = latest, it was added just before the release was dropped.  It isn't currently working in master. #55 represents the underlying problem / reason why it's not working.

**Comment by flavorjones** [comment]
Ah, roger that. I just wanted to make sure we had a story in our backlog for this; I see it now (https://www.pivotaltracker.com/story/show/91010524).
