### ISSUE TITLE
Httpd Version 2.4.53

### ISSUE THREAD

**Issue by cth18012017** [cloudfoundry/php-buildpack#614]
Hello, please implement the new Version of httpd server: 

https://github.com/apache/httpd/releases/tag/2.4.53

**Comment by brayanhenao** [comment]
Hi @cth18012017,

Because these CVEs are not categorized yet (they are being evaluated) we cannot take any action to make a release of the Buildpack following our policies mentioned in my previous comment.

We will keep an eye on these CVEs so that when they are categorized as High or Critical we can take action.

Thanks!

**Comment by brayanhenao** [comment]
@cth18012017 Update, one of the CVEs listed above has been categorized as `Critical`, so we will proceed to release a new version of `PHP Buildpack`.

`HTTPD v2.4.53` is available in the latest version of PHP Buildpack ([v4.4.58](https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.58))
