### ISSUE TITLE
Questions about composer support

### ISSUE THREAD

**Issue by ArthurHlt** [cloudfoundry/php-buildpack#65]
I have some questions about choice made for composer support.
I saw that when you push an app with `composer.json` the buildpack will move this file but also `composer.lock` in `app/` directory inside container and it also move `vendor` directory in `app/lib/`.

I get this buildpack want to use include to load vendor directory and I think too it's to have a better security cause `app/lib/vendor/` will not be accessible by webserver.
As a php developper, I need to make a lot of change in my app to make it enter on Cloud Foundry cause of it, first i need to remove the way how app load the `vendor/autoload.php` in all files (much of them do `include __DIR__ .'/vendor/autoload.php';` ).

 Secondly, if it's a project which use `psr-4` or `psr-0` loading in composer.json (most of recent php app like [Symfony](https://github.com/symfony/symfony) ) as `vendor` directory is not in root project i need to change every psr entries with `htdocs` at the beginning, exemple:
```json
    "autoload": {
        "psr-4": {
            "Symfony\\Bridge\\Doctrine\\": "src/Symfony/Bridge/Doctrine/", //become htdocs/src/Symfony/Bridge/Doctrine/
            "Symfony\\Bridge\\Monolog\\": "src/Symfony/Bridge/Monolog/", // become htdocs/src/Symfony/Bridge/Monolog/
            "Symfony\\Bridge\\ProxyManager\\": "src/Symfony/Bridge/ProxyManager/", // ...
            "Symfony\\Bridge\\Swiftmailer\\": "src/Symfony/Bridge/Swiftmailer/",
            "Symfony\\Bridge\\Twig\\": "src/Symfony/Bridge/Twig/",
            "Symfony\\Bundle\\": "src/Symfony/Bundle/",
            "Symfony\\Component\\": "src/Symfony/Component/"
        },
        "classmap": [
            "src/Symfony/Component/HttpFoundation/Resources/stubs",
            "src/Symfony/Component/Intl/Resources/stubs"
        ],
        "files": [ "src/Symfony/Component/Intl/Resources/stubs/functions.php" ]
    },

```

I feel to far from my origin app and i can't make it run locally if i want to use cloud foundry with it. 
So i just wanted to know why make this choice? Is this for security reason?

If it's for security reason you can do like last php-buildpack did (and also obviously heroku-php-buildpack do), you can chmod to 644 all folders inside vendor.

I really love the work made for this buildpack but i feel really painful to use for composer app and I still want to use this buildpack (and not use heroku-php-buildpack). If there is no special reasons could you let `vendor` directory, `composer.json` and `composer.lock` where they are ? In add, it will be baffling for beginners on cloud foundry.

**Comment by dmikusa-pivotal** [comment]
>I saw that when you push an app with composer.json the buildpack will move this file but also composer.lock in app/ directory inside container and 

Not quite.  The final resting place of the composer.json & composer.lock files should be `app/` (i.e. run `cf files <app> app/` and you should see them).

>it also move vendor directory in app/lib/.

Yes, under some circumstances this could happen.  It doesn't always though.

>As a php developper, I need to make a lot of change in my app to make it enter on Cloud Foundry

The most important thing to take away from this is that you should not need to make changes to your app.  The build pack is flexible and can work with what you have, it just needs a little help.  Please read on.

The  behavior of moving files around only happens when the build pack cannot understand the structure of the application that you've uploaded.  PHP apps can be structured in a ton of different ways.  The build pack applies some basic logic to try and understand what you've uploaded.  If it cannot, then it defaults to doing what you said and applies some basic structure (i.e. creates `htdocs`, moves your stuff there).

If you don't want the build pack to move your files around, which is an understandable wish, you just need to provide it with some additional metadata so that it knows where your public files are located.

To do this, you can provide the build pack through it's config file with a `WEBDIR`.  When the `WEBDIR` directory exists, the build pack **knows where your public files are located and so does not need to move anything around**.  

This option should be the relative path to a directory containing your public files.  By default as I mentioned above, it looks for `htdocs`.  See more at the following link.

https://github.com/cloudfoundry/php-buildpack/blob/master/docs/config.md#optionsjson

As far as the `vendor` directory, that can be changed too.  The build pack allows you to pass the `COMPOSER_VENDOR_DIR` environment variable to Composer.  If you don't set it, it will default to `lib/vendor`, which is the behavior you observed.  If you want to have the `vendor` directory somewhere else, you simply need to set that value.

https://github.com/cloudfoundry/php-buildpack/blob/master/docs/composer.md#configuration

Example for doing both of these things for a Symfony app:  https://github.com/cloudfoundry/php-buildpack/blob/master/cf_spec/fixtures/symfony_hello_world_with_local_dependencies/.bp-config/options.json

>Secondly, if it's a project which use psr-4 or psr-0 loading in composer.json (most of recent php app like Symfony ) as vendor directory is not in root project i need to change every psr entries with htdocs

I have not seen this, but you need to follow the instructions above.  If those don't help, let me know.

>I feel to far from my origin app and i can't make it run locally if i want to use cloud foundry with it. 
So i just wanted to know why make this choice? Is this for security reason?

I don't think the security argument is the main one.  PHP apps can be anything from one `index.php` file to complicated multi-folder projects.  The build pack attempts to do the right thing so that those will all just run, but that does not always happen.  In those cases, you need to give it a little help.

I will say at the moment, that the build pack is skewed towards "just working" for less structured PHP apps (i.e. where you just dump everything into a docroot).  Apps with defined folder structures like Cake or Symfony, often need that little bit of extra help.  This is a place where I'd like to see the build pack get better.  Specifically, I think we can detect some of the more popular frameworks like Cake, Symfony and <insert your framework here>, and automatically adjust the `WEBDIR` and Composer so that dev's don't need to manually make these changes.

**Comment by ArthurHlt** [comment]
Thanks for your (really) complete answer.
I've trying to play with `options.json` with `COMPOSER_VENDOR_DIR` but I didn't use properly.

So ok, I've tried a couple of a thing and i can run this kind of app: [https://github.com/sphring/sphring-microwebframe](https://github.com/sphring/sphring-microwebframe) by using `COMPOSER_VENDOR_DIR` and `WEBDIR` (use `app` as webdir and `vendor` as composer vendor dir).

But there is one problem, if i've already did `composer install` before pushing on Cloud Foundry buildpack or composer (i didn't really troubleshooting which do this error) start to complain about failing on `integrity constraint version ^1.2 ...`. It could be really a problem cause my Cloud Foundry environment has restricted access to web so I want to download dependencies before pushing the app.

I tried an other app to know what can I do with `bp-config.json` to run immediately by forcing myself to make this app running locally and on Cloud Foundry and I can't. You can try to make this app: [https://github.com/ArthurHlt/rest-proxifier](https://github.com/ArthurHlt/rest-proxifier) and this app is an ideal one, she is PaaS ready.

Problems for this app are:
 - There is no `WEBDIR` possible to expose so when I want set `COMPOSER_VENDOR_DIR` to `vendor` this is no sense cause I will not be in the default `WEBDIR`,  I could set `COMPOSER_VENDOR_DIR` to default `vendor` but anyway I can't cause of the second problem.
 - Buildpack will:
    1. Move source in the default `WEBDIR`
    2. Move `composer.json` and `composer.lock` to `BUILD_DIR`
    3. Move vendor directory `BUILD_DIR/COMPOSER_VENDOR_DIR`
    4. And start `composer install {options}` in `BUILD_DIR` 
  This ending command force to write in `composer.json` inside autoload part `{WEBDIR}/src...`. I think it's due to composer with his autoloader. Autoloader by default will create this kind of file:
```php
<?php
// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'orange\\cfhelper\\' => array($vendorDir . '/orange-opensource/cf-helper-php/src/orange/cfhelper'),
    'Stash\\' => array($vendorDir . '/tedivm/stash/src/Stash')
// ....
);
```
but with this buildpack it will become (`dirname` function added for `$baseDir`):
```php
<?php
// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'orange\\cfhelper\\' => array($vendorDir . '/orange-opensource/cf-helper-php/src/orange/cfhelper'),
    'Stash\\' => array($vendorDir . '/tedivm/stash/src/Stash')
// ....
);
```
So i'm forced to make some change to make it run on Cloud Foundry but my app will not work locally.

I really love the work you've made and the work for composer is good for framework if you play a little with `bp-config.json` but it's not really suitable for app which use composer and have no `WEBDIR` (and i'm not the only one who do this :) ).

So my suggestion is to keep your work you've made but by default composer will install as you could do locally (I mean not touch anything just run `composer install {options}` inside `WEBDIR`). And if you want a more advanced managing you change a options to make it works as it's work right now.

I start to do the job here: [https://github.com/ArthurHlt/php-buildpack/blob/master/extensions/composer/extension.py](https://github.com/ArthurHlt/php-buildpack/blob/master/extensions/composer/extension.py) you can take a look if you are interested.

**Comment by hairmare** [comment]
Hi @ArthurHlt 

The ``integrity constraint version ^1.2`` is due to the caret operator only being supported in composer ``1.0.0-alpha10`` which has just been release. Updating it in the buildpack is tracked in #64.

**Comment by dmikusa-pivotal** [comment]
>But there is one problem, if i've already did composer install before pushing on Cloud Foundry buildpack or composer (i didn't really troubleshooting which do this error) start to complain about failing on integrity constraint version ^1.2 .... It could be really a problem cause my Cloud Foundry environment has restricted access to web so I want to download dependencies before pushing the app.

@hairmare hit the nail on the head here.  We'll be updated to support the carrot operator soon.  I believe you can work around this by using >= instead in composer.json.  There was also an option to use the latest "dev" release of Composer, but that is unfortunately broken in the master branch.  If you use the latest release it works though.  Set COMPOSER_VERSION to "latest" and use this build pack.

`cf push -b https://github.com/cloudfoundry/php-buildpack#v3.1.0 ...`

>I tried an other app to know what can I do with bp-config.json to run immediately by forcing myself to make this app running locally and on Cloud Foundry and I can't. You can try to make this app: https://github.com/ArthurHlt/rest-proxifier and this app is an ideal one, she is PaaS ready.

Some thoughts on this below...

>There is no WEBDIR possible to expose so when I want set COMPOSER_VENDOR_DIR to vendor this is no sense cause I will not be in the default WEBDIR, I could set COMPOSER_VENDOR_DIR to default vendor but anyway I can't cause of the second problem.

When you don't set a WEBDIR and you don't have an `htdocs` directory in your project then everything you push will be moved to the `htdocs` directory on CF.  That becomes the WEBDIR (i.e. the docroot).  As far as your vendor directory, this gets moved too so you should set COMPOSER_VENDOR_DIR to `htdocs/vendor`.

This actually seems to get things very close to working on CF.  When I do this, I get this error.

```
2015-04-21T08:35:04.07-0400 [App/0]      OUT 12:35:04 httpd   | [Tue Apr 21 12:35:04.064318 2015] [proxy_fcgi:error] [pid 47:tid 140045363676928] [client 23.28.250.16:17360] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class Arthurh\\RestProxifier\\RestProxifier does not exist' in /home/vcap/app/htdocs/vendor/sphring/sphring/src/Arthurh/Sphring/Model/Bean/AbstractBean.php:189\nStack trace:\n#0 /home/vcap/app/htdocs/vendor/sphring/sphring/src/Arthurh/Sphring/Model/Bean/AbstractBean.php(189): ReflectionClass->__construct('Arthurh\\\\RestPro...')\n#1 /home/vcap/app/htdocs/vendor/sphring/sphring/src/Arthurh/Sphring/Model/Bean/AbstractBean.php(163): Arthurh\\Sphring\\Model\\Bean\\AbstractBean->instanciate()\n#2 /home/vcap/app/htdocs/vendor/sphring/sphring/src/Arthurh/Sphring/Model/Bean/Bean.php(27): Arthurh\\Sphring\\Model\\Bean\\AbstractBean->inject()\n#3 /home/vcap/app/htdocs/vendor/sphring/sphring/src/Arthurh/Sphring/Sphring.php(220): Arthurh\\Sphring\\Model\\Bean\\Bean->inject()\n#4 /home/vcap/app/htdocs/vendor/sphring/sphring/src/Arthurh/Sphring/Sphring.php(209): Arthurh\\Sphring\\Sphring->addBean(Object(Arthurh\\Sphring\\Model\\Bean\\Bean))\n#5 /home/vcap/app/htd...\n'
```

I'm not sure exactly why this is failing, but I'm guessing it has to do with your next point regarding the autoloader.

>And start composer install {options} in BUILD_DIR This ending command force to write in composer.json inside autoload part {WEBDIR}/src.... I think it's due to composer with his autoloader. Autoloader by default will create this kind of file:

This seems to be a discrepancy with Composer.  If you look at the docs, it says the following regarding autoloading.

>The src directory would be in your project root, on the same level as vendor directory is.

https://getcomposer.org/doc/01-basic-usage.md#autoloading

but that doesn't seem to be what's happening here.  We're changing the vendor location, which is legitimate according to the docs, but Composer is not changing the autoloader in the same fashion.  In other words, your `src` directory is located on the same level as the `vendor` directory, but neither are located in the directory where we're running Composer, which in reality appears to be the base path used in the autoloader.

One way to work around this is to simply move the files to where Composer expects them.  I made this work with the following `.bp-config/options.json` and `manifest.yml` files.

```
{
    "COMPOSER_VERSION": "latest",
    "COMPOSER_VENDOR_DIR": "htdocs/vendor",
    "PHP_VERSION": "{PHP_55_LATEST}"
}
```

```
---
applications:
- name: rest-proxifier
  memory: 256M
  host: rest-proxifier-dan
  instances: 1
  path: .
  buildpack: https://github.com/dmikusa-pivotal/cf-php-build-pack.git#v3.1.0
  command: "mv $HOME/htdocs/config $HOME/htdocs/src $HOME/htdocs/view ./ && $HOME/start.sh"
```

Note the "command" which is moving "config", "src" and "view" up a directory.  "src" needs to be moved because the autoloader looks for it there.  "config" and "view" are moved too because your app is creating paths based on the relative location of "src".  Since that moved, those need to move as well.  I didn't do an extensive test of your app, but it did pull up the index page and display an "Admin UI".

The other option would be to use `sed` or a similar tool to rewrite the autoloader.  The difference here is that you're leaving all of your application files under `htdocs` which means they are public.  Personally, I don't like doing that.  The more stuff I can keep out of the docroot, the better.

>it's not really suitable for app which use composer and have no WEBDIR (and i'm not the only one who do this :) ).

I'm not sure that we've seen this particular use case, i.e. no WEBDIR && Composer && autoloader, so I think that's where the rough edges are coming from.  I definitely think we can handle this better and I agree with you.  I think the build pack should probably just move everything to `htdocs` and run Composer from there.  Without a WEBDIR or `htdocs` directory, it doesn't seem safe to run Composer like we're currently doing.

That's easier said than done though.  I'll keep this issue open as a reminder that we need to improve this particular use case (the sample app that is linked above can be used for a demo app).

**Comment by ArthurHlt** [comment]
Thanks for the time you took for this answer and thanks to @hairmare to tell me what's going wrong (I don't use caret I think it's when I `composer install` locally and composer will generate a lock file with some caret).  
Well your solution should work but this is cheating :)

**Comment by hairmare** [comment]
Yeah @ArthurHlt. Using the caret operator is not your fault at all. It is being used by some dependency of yours and is primarily happening due to the fact that composer is telling users to use an untagged version of composer to start with. For lots of people this has been happening due to their use of phpunit that has phpspec/prophecy#176 as a dep containing the issue.

Also about the whole *opinionated* buildpack issue (the ``WEBDIR`` confusion). It really looks like there is need for some change as to how composer apps are being handled. While there are always solutions to these problems, they do seem to pop up often.

@dmikusa-pivotal @flavorjones (or other buildpack folks?) Let me know in what form you want it and I'll try to write a full proposal type document on this.

**Comment by dmikusa-pivotal** [comment]
@hairmare - I don't have a particular preference on format.  If it some specific suggestions or changes, you can submit github issues.  If it's a major overhall, you might look at vcap-dev which has some examples of other proposed changed to CF.  I'd probably go with a similar format / style as those.

As far as change, I'm all for it.  Especially if it's pulling the build pack more inline with the way that the community as a whole does things.

Some thoughts on how I'd like to see things evolve:

  - I think we're in a pretty good spot with the way things work now.  I think it's possible to make most projects and frameworks run with a few adjustments to the build pack config or the manifest.  This showcases the flexibility of the build pack and PHP tools.  Where I think we can do better is in eliminating the need to make manual adjustments.  We can easily detect popular frameworks or file layouts and automatically set things like WEBDIR and LIBDIR.  This will get the BP back to the "it just works" philosophy.

  - The behavior of the build pack when there is a lack of a well define folder structure needs some improvement.  It currently just takes the approach of "no defined docroot, we'll make one and put all of your files in it".  Where things get a little wonky is when you pair this with Composer.  I think that's showcased above and we need to address that.  My $0.02 would be to move the user files to the docroot (i.e. everything you upload is public) and run composer from the docroot.  This should be basically the same as running Composer locally.

Other opinions are certainly welcome.  If they're on topic with this issue, post them here.  Otherwise please open a new issue.
