### ISSUE TITLE
why can a.War format Java application package  with buildpack PHP, stage  successfully?

### ISSUE THREAD

**Issue by wangping710** [cloudfoundry/php-buildpack#76]

**Comment by dmikusa-pivotal** [comment]
Without seeing logs, I can only guess.  It's likely that you pushed the app, it detected a PHP file or composer.json (a third option is that you may have just forced the PHP build pack to run with -b), the staging runs, installing a web server & PHP, and then the web server and PHP are started.  The reason it's not failing is probably because the way the web server is configured.  It serves up any non-PHP files as static files.  The PHP process is still running, but wouldn't get called unless you tried to access a PHP file.

**Comment by flavorjones** [comment]
Closing this question for now, as there doesn't appear to be anything actionable.

@wangping710 please provide additional information if you'd like a deeper answer!
