### ISSUE TITLE
Value set to PHP_BINDIR

### ISSUE THREAD

**Issue by aleej** [cloudfoundry/php-buildpack#83]
Within a deployed PHP app on the buildpack, the constant PHP_BINDIR has a value `/tmp/staged/app/php/bin` which at runtime does not exist.  In fact, the PHP_BINDIR should be in `app/php/bin`.

Is this an expected behavior?

**Comment by dmikusa-pivotal** [comment]
My understanding is that the PHP_BINDIR constant is set a compile time, so I'm not sure how we would fix this.  The path you're reporting, `/tmp/staged/app/php/bin` is correct at compile time and when your application is staged on CF.  It's not likely to be correct at runtime though.  

The problem is that CF creates a droplet from your application bits & what the build pack installs while it runs.  The droplet can then be extracted that to any location when it's run.  At the moment, it's extracted to `/home/vcap/app`, but I believe that path at least in theory could change.

Unless there's a way to tell PHP the correct path at runtime (if you know of one, please let us know), I don't think we could fix this, at least not in the form of a pure fix.  We could certainly change the path at compile time, so that it uses `/home/vcap/app/php`, but that would only fix the issue as long as `/home/vcap/app` is the root where droplets are extracted and that would probably require a non-trivial amount of work.

What's your use case for this, btw?

**Comment by hairmare** [comment]
I'm not sure what ``PHP_BINDIR`` should point to, I've been assuming that ``php`` is on ``PATH``. For me that's what I would call the advertised behaviour of the buildpack.

**Comment by aleej** [comment]
Our use case is to port over some older php code to run within CF.  I believe the code is basically using `exec ()` to call a another php file to do some processing work.  For the `exec ()` call, it is acutally passing PHP_BINDIR/php as the executable. I havent tested what @hairmare stated which is to assume that `php` is on the `PATH` for the buildpack.  In some non-CF environments, that isnt always an assumption 

For our use case, as long as we have a consistent expectation on where the `php` binary would be found.

**Comment by dmikusa-pivotal** [comment]
>I've been assuming that php is on PATH. For me that's what I would call the advertised behaviour of the buildpack.

Correct.  It will be on the PATH, so you can just do `php <your-cmd>`.

**Comment by aleej** [comment]
Aright, we'll go down that route. Thanks for your help @dmikusa-pivotal @hairmare!
