### ISSUE TITLE
"Deploying on a Stack that's not supported by this buildpack" 

### ISSUE THREAD

**Issue by vik-y** [cloudfoundry/php-buildpack#87]
I am getting this error while deploying this service on bluemix. This error was not their about a week ago. Don't know what's wrong. 

Cloning into '/tmp/buildpacks/php-buildpack'...
Submodule 'compile-extensions' (https://github.com/cloudfoundry-incubator/compile-extensions) registered for path 'compile-extensions'
Cloning into 'compile-extensions'...
Submodule path 'compile-extensions': checked out '1f260464c156bddfb654adb14298344797d030a1'
It looks like you're deploying on a stack that's not supported by this buildpack.
That could be because you're using a recent buildpack release on a deprecated stack.
If you're using the buildpack installed by your CF admin, please let your admin know you saw this error message.
If you at one point specified a buildpack that's at git URL, please make sure you're pointed at a version that supports this stack.

**Comment by dmikusa-pivotal** [comment]
See here for troubleshooting steps and a likely explanation:  https://github.com/cloudfoundry/php-buildpack/issues/86

**Comment by vik-y** [comment]
Downgrading to version 3.2.2 worked for me too. Thanks :+1:

**Comment by dmikusa-pivotal** [comment]
Excellent!  Just to be clear, downgrading is on a temporary solution.  By downgrading, you're running a few risks:

1.) The `lucid64` stack, which is likely what you're running, has not been supported supported by Cannonical since 4/30/15 (and consequently not supported by CF).  The farther you get from that date, the more likely there are unpatched vulnerabilities in that stack.

2.) The build packs are not producing new binaries for `lucid64` which means, you won't get the latest PHP, Nginx & Apache HTTPD binaries.  Again, as time progresses it'll be more and more likely that your app will be using code with vulnerabilities.

Ultimately you need to migrate to the `cflinuxfs2` stack.  I don't know the situation with Bluemix, but migration could be as simple as running `cf stacks` to confirm that `cflinuxfs2` is available and adding the `-s cflinuxfs2` argument to `cf push` the next time you run it.

**Comment by vik-y** [comment]
I didn't know it was that easy to change the stack. I did it and it's working fine for me now on Bluemix. :+1:

**Comment by jsloyer** [comment]
Is there a way to to default to `cflinuxfs2` instead of getting the error message saying `lucid64` is not supported?

**Comment by dmikusa-pivotal** [comment]
@jsloyer - It's not up to the build pack to pick the stack.  It just works with the stack it's given.

If you're an application developer, you can use the default stack or set one with cf cli or via manifest.yml.

It's up to the CF operator to set the default stack.  I don't know how to do that offhand.  You could ask on the cf-dev list, I'm sure someone there can point you in the right direction.
