### ISSUE TITLE
Version 4.0.0: PHP startup warnings

### ISSUE THREAD

**Issue by mfeltscher** [cloudfoundry/php-buildpack#93]
Hi there

When using version 4.0.0 of the buildpack, I get some strange PHP startup warnings:
```PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/tokenizer.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/tokenizer.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/dom.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/dom.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/json.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/json.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/pcre.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/pcre.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/reflection.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/reflection.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/spl.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/spl.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/xmlwriter.so' - /tmp/staged/app/php/lib/php/extensions/no-debug-non-zts-20121212/xmlwriter.so: cannot open shared object file: No such file or directory in Unknown on line 0```

My application seems to work just fine afterwards. I haven't encountered this problem with version 3.3.1. Can you tell me, what's causing this?

Thanks
Moreno

**Comment by dmikusa-pivotal** [comment]
Your application is including PHP extensions that do not exist.  It looks like most or all of these are just compiled into PHP statically so there no need to included them as extensions.  If you're specifying these in `.bp-config/options.json` you can simply remove them from that list and the errors should go away.  If you're requiring them in your `composer.json` file you can remove them as well.  If they're being pulled in through Composer from dependent projects then there's not much you can do but ignore them.

I believe this is a side effect of the build pack switching to one large binary.  [Previously it would download individual extension and filter out extensions that don't exist](https://github.com/cloudfoundry/php-buildpack/commit/edb06cb0b77afe82a478a2e40e378c73697c68a8).  It would be nice to add back in some filtering like that, but it's tricky because it requires knowledge of every available PHP extension for every set of binaries.

**Comment by mfeltscher** [comment]
In my case these are getting pulled in through Composer from dependent projects - so not much I can do about.

**Comment by flavorjones** [comment]
@mfeltscher Do you think that this change will make your errors go away?

> https://www.pivotaltracker.com/story/show/99170278

This is on the `develop` branch right now, if you'd like to try.

**Comment by mfeltscher** [comment]
Hi @flavorjones 

I don't think this is related. I don't want to disable composer and my composer.json file should be evaluated upon startup as it does now. Some of my dependencies are requiring extensions which are built into PHP statically and therefore a warning is getting shown.

**Comment by flavorjones** [comment]
I'm going to ask the buildpacks team to look into replacing the previous logic (which disabled extensions that weren't present) with something that works with the current packaging.

**Comment by flavorjones** [comment]
Fixed behavior will be in php-buildpack 4.1.0, see here for status: https://www.pivotaltracker.com/story/show/102019942

**Comment by mfeltscher** [comment]
Tested in version 4.1.2, works like a charm! Thanks!

**Comment by flavorjones** [comment]
Great! Thank you for following up!
