### ISSUE TITLE
NGINX modules

### ISSUE THREAD

**Issue by decanus** [cloudfoundry/php-buildpack#98]
Hey, quick questions.
Is there a way to complie nginx with modules like WebDAV?

**Comment by dmikusa-pivotal** [comment]
Yes, although it's a bit of work.

Steps:

 - Fork this project:  https://github.com/cloudfoundry/binary-builder  It's what builds the binaries.
 - Modify [this template](https://github.com/cloudfoundry/binary-builder/blob/master/templates/nginx_blueprint.sh.erb#L12-L25) and change the `./configure` options to your liking.
 - Follow [instructions](https://github.com/cloudfoundry/binary-builder#running-within-docker) to run and build Nginx.
 - Upload Nginx files to some HTTP server, so they're accessible to the CF instance you're targeting.
 - Fork the PHP build pack.
 - Modify the `manifest.yml` [here](https://github.com/cloudfoundry/php-buildpack/blob/master/manifest.yml#L77-L94).  Change the URI & MD5 for the version of Nginx you built.
 - Commit your change to your fork of the build pack
 - Point your application to your forked build pack

Because this requires you to fork `binary-builder` and `php-buildpack`, make sure that you monitor those going forward and periodically [merge in upstream changes](https://help.github.com/articles/syncing-a-fork/).  Failure to do so could leave you with binaries or a build pack that is out-of-date or missing critical fixes.

**Comment by decanus** [comment]
Hey, awesome thanks
